server:
  port: 8888

spring:
  security:
    user:
      name: user
      password: password
  application:
    name: typhoon-admin-server
  boot:
    admin:
      ui:
        title: 服务监控中心

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "user"
      user.password: "password"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
