server:
  port: 8083
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/typhoon?characterEncoding=utf8&useSSL=true
    username: root
    password: field
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: typhoon-query

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.field.typhoonquery.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#配置eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
