spring:
  application:
    name: typhoon-eureka-client
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: user
        password: password

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
