
spring:
  application:
    name: typhoon-download
  #Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: user
        password: password

#Spring Boot Admin health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#配置eureka server
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/

server:
  port: 8079
